name: L5Kit docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: l5kit
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build docs
      working-directory: .
      run: |
        sphinx-apidoc --module-first --separate -o API/ l5kit/l5kit l5kit/l5kit/tests*
        sphinx-build . html
